# Generated by Django 4.1.5 on 2023-07-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiestand',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
